// render_gates.cjs -- render docs/GATES.md from the append-only ledger evidence/gates.ndjson.
// The ledger is the SOURCE OF TRUTH (also live-consumed by viewer/infra.cjs); GATES.md is the
// human-readable rendered view. Current verdict per gate = the LAST row bearing that name (append-only
// supersede). Run: node viewer/render_gates.cjs   (writes docs/GATES.md; prints the tally).
"use strict";
const fs = require("fs");
const path = require("path");
const REPO = path.join(__dirname, "..");
const LEDGER = path.join(REPO, "evidence", "gates.ndjson");
const OUT = path.join(REPO, "docs", "GATES.md");

const rows = fs.readFileSync(LEDGER, "utf8").split(/\r?\n/).filter(Boolean)
  .map((l) => { try { return JSON.parse(l); } catch (_) { return null; } }).filter(Boolean);

// group by name in first-appearance (chronological) order; current = last row for that name.
const order = [];
const cur = new Map();
let superseded = 0;
for (const r of rows) {
  const name = r.name || r.gate || r.id;
  if (!name) continue;
  if (!cur.has(name)) order.push(name); else superseded++;
  cur.set(name, r);
}

const VERDICTS = ["PASS", "PARTIAL", "FAIL", "WITHHELD", "PENDING"];
const tally = Object.fromEntries(VERDICTS.map((v) => [v, 0]));
for (const name of order) { const v = (cur.get(name).verdict || "PENDING").toUpperCase(); if (tally[v] === undefined) tally[v] = 0; tally[v]++; }

function link(rp) {
  if (!rp) return "—";
  const base = path.basename(rp);
  const href = rp.startsWith("docs/") ? rp.slice("docs/".length) : ("../" + rp);
  return `[${base}](${href})`;
}
function esc(s) { return String(s == null ? "" : s).replace(/\|/g, "\\|"); }

const tallyLine = VERDICTS.filter((v) => tally[v]).map((v) => `**${tally[v]} ${v}**`).join(" · ");
const lines = [];
lines.push("# UNI Gate Registry (rendered)");
lines.push("");
lines.push("**Source of truth:** `evidence/gates.ndjson` (append-only NDJSON, one row per gate, schema `production/schemas/gate_row.schema.json`).");
lines.push("**Do not edit this file by hand.** It is the rendered view of the ledger. To change a verdict, append a new row to `evidence/gates.ndjson` (never mutate an old row) and re-render with `node viewer/render_gates.cjs`.");
lines.push("");
lines.push("**Verdict vocabulary (canonical, never percent-scored):** `PASS` / `PARTIAL` / `FAIL` / `WITHHELD` / `PENDING`.");
lines.push("**Evidence classes:** A = independently reproduced, B = observed-with-artifact, C = command-output, Sec = security-relevant-unproven, pending = not-yet-established.");
lines.push("");
lines.push("---");
lines.push("");
lines.push("## Live gate ladder");
lines.push("");
lines.push(`${order.length} unique gates (${rows.length} total rows in the ledger; ${superseded} are historical/superseded revisions of the same gate name). Current tally by name: ${tallyLine}.`);
lines.push("");
lines.push("| Gate | Phase | Verdict | Class | Receipt |");
lines.push("|---|---|---|---|---|");
for (const name of order) {
  const r = cur.get(name);
  const verdict = (r.verdict || "PENDING").toUpperCase();
  lines.push(`| **${esc(name)}** | ${esc(r.phase || "—")} | **${verdict}** | ${esc(r.evidence_class || "—")} | ${link(r.receipt_path)} |`);
}
lines.push("");
fs.writeFileSync(OUT, lines.join("\n") + "\n");
console.log(`rendered docs/GATES.md: ${order.length} gates (${rows.length} rows, ${superseded} superseded) -> ${tallyLine.replace(/\*\*/g, "")}`);
